### ISSUE TITLE
Feature Request: Automatic Reload

### ISSUE THREAD

**Issue by alexandrev** [k0kubun/Nocturn#26] opened 2016-09-04 14:08 UTC
Configuration parameter to do a automatic refresh.

**Comment by k0kubun** [comment] 2016-09-04 14:24
Periodically? How frequently do you want to reload? 

And what's the purpose of that? Timeline tab is refreshed in real time until the streaming connection fails. So do you want to reload other tabs automatically or refresh the timeline streaming?

**Comment by alexandrev** [comment] 2016-09-04 14:40
On my Mac it is not refreshed automatically. It waits until I press cmd + r.

Regards,

**Comment by k0kubun** [comment] 2016-09-04 14:54
Timeline streaming is a built-in feature. Could you try restarting Nocturn or waiting after pressing cmd+r? The streaming is also refreshed after cmd+r.

**Comment by alexandrev** [comment] 2016-09-04 15:05
On my machine only refresh when I press the button. Nothing else.

**Comment by k0kubun** [comment] 2016-09-04 15:55
Hmm, it's difficult to resolve since the problem can't be reproduced on my machine. Can you use streaming on other desktop Twitter client?

**Comment by k0kubun** [comment] 2016-10-03 14:01
In addition to "Timeline" tab update, I implemented real time update for "Search" tab too. https://github.com/k0kubun/Nocturn/pull/39

Closing for now but feel free to reopen this if you can't reproduce a streaming timeline only on Nocturn.

**Closed by k0kubun** 2016-10-03 14:01 UTC

**Comment by k0kubun** [comment] 2016-11-17 16:35
Finally I experience the same issue and it was resolved by fixing hardware clock. My clock was 5-minutes early.
