### ISSUE TITLE
Bug validate login.

### ISSUE THREAD

**Issue by DaviRamosAndrade** [k0kubun/Nocturn#42] opened 2016-10-14 22:02 UTC
[
![screenshot from 2016-10-14 18-55-38](https://cloud.githubusercontent.com/assets/5041033/19403909/9c93d94a-9240-11e6-898d-2e03c024b6d3.png)
](url)

**Comment by Equinox** [comment] 2016-10-14 22:09
Looks like a duplicate of https://github.com/k0kubun/Nocturn/issues/25.

**Comment by k0kubun** [comment] 2016-10-15 01:08
Fixed this issue on Nocturn v1.4.2. Could you try it?

**Closed by k0kubun** 2016-10-15 01:08 UTC
